### ISSUE TITLE
Better nunaliit command option processing

### ISSUE THREAD

**Issue by jpfiset** [GCRC/nunaliit#427] opened 2016-01-11 21:14 UTC
There are no warnings associated with unrecognized options in the nunaliit command line utility. This leads to confusion. For example:

nunaliit dump --overwrite_docs

In this case, the option should be rejected since the correct form is "--overwrite-docs"

**Comment by ahayes** [comment] 2016-01-11 21:58
Duplicate of #424

Beat you to it! :)

**Closed by ahayes** 2016-01-11 21:58 UTC
Labels: enhancement
