### ISSUE TITLE
No way to set/remove default translation languages

### ISSUE THREAD

**Issue by billingb** [GCRC/nunaliit#856] opened 2020-01-14 19:58 UTC
I have not been able to find any good, documented way to set the languageService languages when wanting the options to be English and Russian. Ideally there would be a way to set the languages, but alternatively a remove method would be good. The solution I came up with (which seems hacky to me) is:

//Remove french, add Russian
    config.directory.languageService.languages.pop();
    var langDef = {
      code: 'ru',
      name: 'русский язык'
    };
    config.directory.languageService.addLanguage(langDef);

**Comment by ahayes** [comment] 2020-01-14 21:18
Duplicate of #812

**Closed by ahayes** 2020-01-14 21:18 UTC
Labels: Duplicate
