### ISSUE TITLE
User management list roles very slow

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#392] opened 2015-10-16 15:29 UTC
When using the User management tool, clicking on a user's 'roles' button opens a dialog with spinning wheel that takes several minutes to fetch the list of roles.

**Comment by pulsifer** [comment] 2015-10-16 16:28
This has also been my experience.

**Comment by jpfiset** [comment] 2015-10-19 15:26
Can you please provide me with a an atlas where this behaviour is observed?

**Comment by jpfiset** [comment] 2015-10-19 15:26
The normal delay that I perceive is about 3 seconds.

**Comment by jpfiset** [comment] 2015-10-19 16:38
This has been addressed in Issue #243. Are you reporting this on an atlas older than this fix?

I am basically unable to reproduce this problem on my platform.

**Comment by ahayes** [comment] 2015-10-19 17:32
This was happening last week on Gwich'in. After several attempts with several users, eventually I gave up (never did come back with the list, even after 30 minutes.)

Later that afternoon, it worked after a few seconds.

**Comment by jpfiset** [comment] 2015-10-19 18:33
Looking at the thule atlas, I experience the same delay. When logging in as 'admin' on the CouchDb futon app and selecting 'status', the app reports indexing of a back up copy of thule (thule_20151016_02).

Obtaining the list of roles is a database wide operation. The algorithm is to iterate over all databases, find the name for each database and find the layers for each database. Then, from this information, it is possible to create a complete list of all roles.

However, getting a list of layers in a database is a view query. If a database has not been indexed yet, then the query does not return until the indexing is done. Obviously, this induces a timeout in the client request, which takes about a minute. Furthermore, this timeout does not seem to be respected by the client application.

**Comment by ahayes** [comment] 2015-10-19 18:49
Ha! I wondered about that. I was making a couple replicated backups each day. Of course, the first (and maybe only?) time those backup db instances would be asked to create their indices would be when that role dialog was hit.

**Comment by jpfiset** [comment] 2015-10-19 19:05
One solution is to have a robot thread hitting all databases, keeping them indexed.

A simpler solution is to change the role dialog to report all roles already set on the user plus all the possible roles for the *current* database.

**Comment by ahayes** [comment] 2015-10-19 19:14
Your second solution sounds best for this issue.

That said, something that pokes the active db to create indices so users don't hit the delays after a reboot would be good for the current database, regardless. But that is a different problem (that isn't as big a deal because I'm already using a web site monitoring service that hits our active atlases regularly.)

**Closed** 2015-10-19 20:24 UTC
Labels: bug
