### ISSUE TITLE
Import profile layer defaults being applied

### ISSUE THREAD

**Issue by ahayes** [GCRC/nunaliit#442] opened 2016-02-05 15:59 UTC
When a layer is specified in an import profile, documents wind up with both the specified layer and the public layer defined. Only the specified layer(s) should be set.

**Comment by boikle** [comment] 2016-08-25 21:10
I tried to reproduce this bug and wasn't able to. Is this still a bug?

**Comment by boikle** [comment] 2017-11-02 19:09
It was pointed out to me recently that this remains an issue when making documents in a different ways. 

**Observed Behaviour:**
* If you create a document via the create document widget, the inital layer(s) which are set in the definition.json file, are the layer(s) is being stored in the new document. 
* However if you create a document with the add or edit a map feature button, only the public layer is applied and the initial layer(s) appear to be ignored.

**Comment by ahayes** [comment] 2017-11-02 22:52
@boikle Can you try one more time with latest and if you can't see it, go ahead and close it.

**Comment by pulsifer** [comment] 2017-11-02 23:37
This will be very important for us soon as we are aiming to use this feature with the Add Feature function from the map interface.  If it is fixed, can I arrange to get a SNAPSHOT to do an upgrade.

Thx

**Comment by boikle** [comment] 2017-11-03 21:04
I did some testing on this and I'm seeing this bug when importing JSON documents (GeoJson docs appear to be imported correctly (see scenario 2 for a possible exception)). 

**Observations:**

***Scenario 1***: When the import profile layer name matches the schema’s initial layer, the following happens;
* The GeoJson import, results in the expected single layer being assigned to the imported documents. (e.g. if the import profile and schema had the default layer set to "mountain", all imported documents would be on the ["mountain"] layer). 
* The Json import, resulted in both the "public" layer and the specified layer being assigned to the imported documents. (e.g. if the import profile and schema had the default layer set to "mountain", all documents would be on the ["mountain","public"] layers). 

***Scenario 2***: When the import profile layer name doesn't match the schema’s initial layer, the following happens;
* The GeoJson import, results in both layers being assigned to the imported documents (e.g. if the schema had a default layer of "mountain" and the import profile had a layer name of "hill", the imported documents would have a nunaliit_layers value of ["hill","mountain"]). I'm not sure if this is the correct behaviour or not. Should the import profile always override the schema defined layers, or should both be added as the result above showed? I can see arguments for either to occur, so I'm not sure if this is the intended behaviour or not. 
* The Json import, results are the same as in Scenario 1, even if the schema's default layer is not set to "public". (e.g. schema has an initial layer defined as "mountain" and the import profile has a layer name of "hill", the resulting import documents would have "public" and "hill" assigned as the layers).

**Comment by boikle** [comment] 2019-10-07 18:58
Can't reproduce this bug

**Closed by boikle** 2019-10-07 18:58 UTC
Labels: Bug
